### ISSUE TITLE
RHEL8 selinux status

### ISSUE THREAD

**Issue by sungju** [sungju/pycrashext#12]
https://github.com/sungju/pycrashext/blob/0f39f105c69d6ef7493a172c2af7eba808fb5d4a/source/selinuxinfo.py#L45

You could use the below steps. Please verify if it is the correct way before implement it.

crash> mount | grep selinuxfs
ffff96c1eb401c80 ffff96c1eca2d000 selinuxfs selinuxfs /sys/fs/selinux
crash> super_block.s_fs_info ffff96c1eca2d000
  s_fs_info = 0xffff96bfc5cfa900
crash> selinux_fs_info.state 0xffff96bfc5cfa900
  state = 0xffffffff96e700c0
crash> struct selinux_state 0xffffffff96e700c0
struct selinux_state {
  disabled = false, 
  enforcing = true, 
  checkreqprot = false, 
  initialized = true, 
  policycap = {true, true, true, false, true, true}, 
  avc = 0xffffffff96e6e8a0, 
  ss = 0xffffffff96e74dc0
}

**Comment by amtdas** [comment]
Ack, seems 'selinux_enforcing' and 'selinux_disabled' kernel symbol does not exists for v4.18 kernel. Alternate kernel symbols are introduced for those two; will check and get back here. Thanks

**Comment by sungju** [comment]
Above steps will give you the same output as 'selinux_enforcing' and 'selinux_disabled' as you can see in the above.

**Comment by amtdas** [comment]
Please assign this bug to me. Thanks.

**Comment by sungju** [comment]
Close due to inactivity
