### ISSUE TITLE
The value in meminfo -i is a page unit

### ISSUE THREAD

**Issue by rhn-jaeshin** [sungju/pycrashext#13]
I have noticed that the value in meminfo -i is indicated as page unit for some of items such as Inactive/Active and etc.

crash> meminfo -i
MemTotal:              527556356 kB
MemFree:                 6253764 kB
MemAvailable:           11973296 kB
Buffers:                     140 kB
Cached:                   679808 kB
SwapCached:                  333 kB
Active:                  2482413 kB
Inactive:              126942379 kB
Active(anon):            2354272 kB
Inactive(anon):        126908443 kB
Active(file):             128141 kB
Inactive(file):            33936 kB
Unevictable:                   0 kB
Mlocked:                       0 kB
SwapTotal:              33554428 kB
SwapFree:               13278772 kB
Dirty:                        34 kB
Writeback:                     0 kB
Mapped:                   175164 kB
Shmem:                     31640 kB
Slab:                          0 kB
PageTables:              1107528 kB
Bounce:                        0 kB
WritebackTmp:                  0 kB
CommitLimit: 36893488144264331264 kB
Committed_AS:          554251492 kB
VmallocTotal:     75078196445184 kB
VmallocUsed:           778047488 kB
VmallocChunk:     39893809082368 kB
Percpu:                      163 kB
HardwareCorrupted:             0 kB
HugePages_Total:               0
HugePages_Free:                0
HugePages_Rsvd:                0
HugePages_Surp:                0
Hugepagesize:               2048 kB
DirectMap2M:          1226512384 kB
DirectMap4M:           609673216 kB

crash> kmem -V|grep NR_INA
          NR_INACTIVE_ANON: 126908443
          NR_INACTIVE_FILE: 33936

crash> pd 126908443+33936
$2 = 126942379

The value in meminfo -i :
Inactive:              126942379 kB

It needs to be converted from page unit to kB (i.e page unit * 4).
Thanks,

**Comment by sungju** [comment]
Thanks for reporting this. It is fixed with b3280db9af249c2f08b7b92c917a802f945ed692. Thanks.
